<html>
	<body>
		<form method="POST" action="https://mobileapps.kbcard.com:15000/CXHIAMKC0035.cms">
			<input type="hidden" name="mainCC" value="b"/>
			<input type="hidden" name="homeZipGubun" value="2"/>
			<input type="hidden" name="homeStandardYN" value="1"/>
			<input type="hidden" name="homeLevel1Serno" value="01"/>
			<input type="hidden" name="homeRoadNameZipCode" value="114404139348"/>
			<input type="hidden" name="homeRoadNameSubZipCode" value="00001"/>
			<input type="hidden" name="homeRoadNameAreaCode" value=""/>
			<input type="hidden" name="homeRoadNameZipCodeSerno" value="01"/>
			<input type="hidden" name="homeUndergroundFlowYN" value="0"/>
			<input type="hidden" name="homeBuildingMainNo" value="20"/>
			<input type="hidden" name="homeBuildingSubNo" value="0"/>
			<input type="hidden" name="homeBuildingManagementNo" value="1144012600100820002021361"/>
			<input type="hidden" name="homeLevel2RoadNameDtailAddress" value="%28%EC%A4%91%EB%8F%99%29"/>
			<input type="hidden" name="homeAddrChgYn" value="Y"/>
			<input type="hidden" name="companyZipGubun" value="2"/>
			<input type="hidden" name="companyStandardYN" value=""/>
			<input type="hidden" name="companyLevel1Serno" value=""/>
			<input type="hidden" name="companyRoadNameZipCode" value="115304148327"/>
			<input type="hidden" name="companyRoadNameSubZipCode" value="00001"/>
			<input type="hidden" name="companyRoadNameAreaCode" value=""/>
			<input type="hidden" name="companyRoadNameZipCodeSerno" value=""/>
			<input type="hidden" name="companyUndergroundFlowYN" value=""/>
			<input type="hidden" name="companyBuildingMainNo" value=""/>
			<input type="hidden" name="companyBuildingSubNo" value=""/>
			<input type="hidden" name="companyBuildingManagementNo" value=""/>
			<input type="hidden" name="companyLevel2RoadNameDtailAddress" value=""/>
			<input type="hidden" name="companyAddrChgYn" value=""/>
			<input type="hidden" name="etczipcode_gubun_code" value=""/>
			<input type="hidden" name="sEtcAddr1" value=""/>
			<input type="hidden" name="etcser_no" value="0"/>
			<input type="hidden" name="etcstreetname_eupmyun_seq" value=""/>
			<input type="hidden" name="etcstreetname_manage_num" value=""/>
			<input type="hidden" name="etcstreetname_area_code" value=""/>
			<input type="hidden" name="etcstreetname_zipcode" value=""/>
			<input type="hidden" name="etcbuilding_major_num" value=""/>
			<input type="hidden" name="etcbuilding_minor_num" value=""/>
			<input type="hidden" name="etcbuilding_manage_num" value=""/>
			<input type="hidden" name="etcjiha_yn" value=""/>
			<input type="hidden" name="etcstreetname_detail" value=""/>
			<input type="hidden" name="strKBrecvName" value="%EC%9E%90%ED%83%9D"/>
			<input type="hidden" name="strOwhusAddrUtznAbilYn" value="1"/>
			<input type="hidden" name="strOwhusTelUtznAbilYn" value="0"/>
			<input type="hidden" name="strWplcAddrUtznAbilYn" value="1"/>
			<input type="hidden" name="strWplcTelUtznAbilYn" value="1"/>
			<input type="hidden" name="strPtablTelUtznAbil" value="1"/>
			<input type="hidden" name="strEtcAddrUtznAbilYn" value=""/>
			<input type="hidden" name="sHouseZip" value="03934"/>
			<input type="hidden" name="sHouse" value="%EC%84%9C%EC%9A%B8+%EB%A7%88%ED%8F%AC%EA%B5%AC+%EC%A4%91%EB%8F%99"/>
			<input type="hidden" name="sHouse1" value="82-2%EB%B2%88%EC%A7%80+102%ED%98%B8"/>
			<input type="hidden" name="sHouseTel" value=""/>
			<input type="hidden" name="sOfficeName" value="%EC%97%90%EC%8A%A4%EC%97%90%EC%8A%A4%EC%95%8C"/>
			<input type="hidden" name="sOfficeName1" value="%EC%BB%A8%EC%84%A4%ED%8C%85"/>
			<input type="hidden" name="sOfficeZip" value="08390"/>
			<input type="hidden" name="sOffice" value="%EC%84%9C%EC%9A%B8+%EA%B5%AC%EB%A1%9C%EA%B5%AC+%EB%94%94%EC%A7%80%ED%84%B8%EB%A1%9C26%EA%B8%B8+111"/>
			<input type="hidden" name="sOffice1" value="%2C102%ED%98%B8+%28%EA%B5%AC%EB%A1%9C%EB%8F%99%2C+%EC%A0%9C%EC%9D%B4%EC%95%A4%EC%BC%80%EC%9D%B4%EB%94%94%EC%A7%80%ED%84%B8%ED%83%80%EC%9B%8C%29"/>
			<input type="hidden" name="sEtcZip" value=""/>
			<input type="hidden" name="sEtcCompName" value=""/>
			<input type="hidden" name="sOfficeTel" value=""/>
			<input type="hidden" name="sTempKBEmail" value="TJDWNS%40naver.com"/>
			<input type="hidden" name="KB_emailAddr1" value=""/>
			<input type="hidden" name="KB_emailAddr2" value=""/>
			<input type="hidden" name="sBCEmail" value=""/>
			<input type="hidden" name="sMphone" value=""/>
			<input type="hidden" name="strHomePostSerno" value="1"/>
			<input type="hidden" name="strOfficePostSerno" value="1"/>
			<input type="hidden" name="sHouseTel1" value=""/>
			<input type="hidden" name="sHouseTel2" value=""/>
			<input type="hidden" name="sHouseTel3" value=""/>
			<input type="hidden" name="sOfficeTel1" value=""/>
			<input type="hidden" name="sOfficeTel2" value=""/>
			<input type="hidden" name="sOfficeTel3" value=""/>
			<input type="hidden" name="sMphone1" value=""/>
			<input type="hidden" name="sMphone2" value=""/>
			<input type="hidden" name="sMphone3" value=""/>
			<input type="hidden" name="homeBaseAddress_hidden" value="%EC%84%9C%EC%9A%B8+%EB%A7%88%ED%8F%AC%EA%B5%AC+%EC%84%B1%EC%95%94%EB%A1%9C9%EC%95%88%EA%B8%B8+20"/>
			<input type="hidden" name="homeDtailAddress_hidden" value="%28%EC%A4%91%EB%8F%99%29"/>
			<input type="hidden" name="companyBaseAddress_hidden" value="%EC%84%9C%EC%9A%B8+%EA%B5%AC%EB%A1%9C%EA%B5%AC+%EB%94%94%EC%A7%80%ED%84%B8%EB%A1%9C26%EA%B8%B8+111"/>
			<input type="hidden" name="companyDtailAddress_hidden" value="%2C102%ED%98%B8+%28%EA%B5%AC%EB%A1%9C%EB%8F%99%2C+%EC%A0%9C%EC%9D%B4%EC%95%A4%EC%BC%80%EC%9D%B4%EB%94%94%EC%A7%80%ED%84%B8%ED%83%80%EC%9B%8C%29"/>
			<input type="hidden" name="officeName_hidden" value="%EC%97%90%EC%8A%A4%EC%97%90%EC%8A%A4%EC%95%8C"/>
			<input type="hidden" name="officeName1_hidden" value="%EC%BB%A8%EC%84%A4%ED%8C%85"/>
			<input type="hidden" name="sOnetel" value=""/>
			<input type="hidden" name="threeAddrBaseAddress_hidden" value=""/>
			<input type="hidden" name="threeAddrDtailAddress_hidden" value=""/>
			<input type="hidden" name="threeAddrOfficeName_hidden" value=""/>
			<input type="hidden" name="threeAddrOfficeName1_hidden" value=""/>
			<input type="hidden" name="sThreeAddrTel" value=""/>
			<input type="hidden" name="sThreeAddrName" value=""/>
			<input type="hidden" name="sThreeAddrName1" value=""/>
			<input type="hidden" name="threeAddrZipGubun" value=""/>
			<input type="hidden" name="threeAddrRoadNameZipCode" value=""/>
			<input type="hidden" name="threeAddrRoadNameAreaCode" value=""/>
			<input type="hidden" name="threeAddrRoadNameSubZipCode" value=""/>
			<input type="hidden" name="threeAddrRoadNameZipCodeSerno" value=""/>
			<input type="hidden" name="threeAddrUndergroundFlowYN" value=""/>
			<input type="hidden" name="threeAddrBuildingMainNo" value=""/>
			<input type="hidden" name="threeAddrBuildingSubNo" value=""/>
			<input type="hidden" name="threeAddrBuildingManagementNo" value=""/>
			<input type="hidden" name="threeAddrLevel2RoadNameDtailAddress" value=""/>
			<input type="hidden" name="threeAddrStandardYN" value=""/>
			<input type="hidden" name="threeAddrLevel1Serno" value="0"/>
			<input type="hidden" name="threeAddrRoadNameZipCode" value=""/>
			<input type="hidden" name="threeAddrAddrChgYn" value=""/>
			<input type="hidden" name="encHomePhoneNo" value="VTJGc2RHVmtYMS9RQTFMWVNyVXZaWC9WZzFQT2F3bjFKMERFQkhvRmZtMD0%3D"/>
			<input type="hidden" name="encCompanyPhoneNo" value="VTJGc2RHVmtYMThISzY3UENXMDBnZkl6aXd1WUdnNFNkbmp2bE9jRHZQZz0%3D"/>
			<input type="hidden" name="encThreeAddrPhoneNo" value=""/>
			<input type="hidden" name="encEmail" value="VTJGc2RHVmtYMS9HMFhHdTNNSzVZN2xzVmcxQnplNnE5ZU1lTUVqRDlMRldFUVJxRTEvV2tFQnp1K2dyRlVHdw%3D%3D"/>
			<input type="hidden" name="isModOfficeTel" value="Y"/>
			<input type="hidden" name="isModHouseTel" value="Y"/>
			<input type="hidden" name="isModthreeAddrTel" value="Y"/>
			<input type="hidden" name="billingPost" value=""/>
			<input type="hidden" name="billingAddrDetail" value=""/>
			<input type="hidden" name="cellPhoneNo" value="VTJGc2RHVmtYMS9ZczZjU3lXejN5Z1VYZkwvbUpKUml4NVJVMlR2ZzdCZz0%3D"/>
			<input type="hidden" name="homeFirstZipCode" value="03934"/>
			<input type="hidden" name="homeBaseAddress" value="%EC%84%9C%EC%9A%B8+%EB%A7%88%ED%8F%AC%EA%B5%AC+%EC%84%B1%EC%95%94%EB%A1%9C9%EC%95%88%EA%B8%B8+20"/>
			<input type="hidden" name="homeDtailAddress" value="%28%EC%A4%91%EB%8F%99%29"/>
			<input type="hidden" name="homePhoneNo" value=""/>
			<input type="hidden" name="officeName" value="%EC%97%90%EC%8A%A4%EC%97%90%EC%8A%A4%EC%95%8C"/>
			<input type="hidden" name="officeName1" value="%EC%BB%A8%EC%84%A4%ED%8C%85"/>
			<input type="hidden" name="companyFirstZipCode" value="08390"/>
			<input type="hidden" name="companyBaseAddress" value="%EC%84%9C%EC%9A%B8+%EA%B5%AC%EB%A1%9C%EA%B5%AC+%EB%94%94%EC%A7%80%ED%84%B8%EB%A1%9C26%EA%B8%B8+111"/>
			<input type="hidden" name="companyDtailAddress" value="%2C102%ED%98%B8+%28%EA%B5%AC%EB%A1%9C%EB%8F%99%2C+%EC%A0%9C%EC%9D%B4%EC%95%A4%EC%BC%80%EC%9D%B4%EB%94%94%EC%A7%80%ED%84%B8%ED%83%80%EC%9B%8C%29"/>
			<input type="hidden" name="companyPhoneNo" value=""/>
			<input type="hidden" name="email" value=""/>
			<input type="submit" value="Submit">
		</form>
	</body>
<html>
